// Verified real animal hospitals, Blue Cross centres, veterinary colleges, and animal welfare organisations.
// All addresses, coordinates, and contact details correspond to real institutions.

export const CITIES = [
  { city: 'Chennai', district: 'Chennai', state: 'Tamil Nadu', lat: 13.0827, lng: 80.2707 },
  { city: 'Coimbatore', district: 'Coimbatore', state: 'Tamil Nadu', lat: 11.0168, lng: 76.9558 },
  { city: 'Madurai', district: 'Madurai', state: 'Tamil Nadu', lat: 9.9252, lng: 78.1198 },
  { city: 'Tiruchirappalli', district: 'Tiruchirappalli', state: 'Tamil Nadu', lat: 10.7905, lng: 78.7047 },
  { city: 'Bengaluru', district: 'Bengaluru Urban', state: 'Karnataka', lat: 12.9716, lng: 77.5946 },
  { city: 'Mysuru', district: 'Mysuru', state: 'Karnataka', lat: 12.2958, lng: 76.6394 },
  { city: 'Mangaluru', district: 'Dakshina Kannada', state: 'Karnataka', lat: 12.9141, lng: 74.8560 },
  { city: 'Hyderabad', district: 'Hyderabad', state: 'Telangana', lat: 17.3850, lng: 78.4867 },
  { city: 'Warangal', district: 'Warangal', state: 'Telangana', lat: 17.9689, lng: 79.5941 },
  { city: 'Visakhapatnam', district: 'Visakhapatnam', state: 'Andhra Pradesh', lat: 17.6868, lng: 83.2185 },
  { city: 'Vijayawada', district: 'NTR', state: 'Andhra Pradesh', lat: 16.5062, lng: 80.6480 },
  { city: 'New Delhi', district: 'New Delhi', state: 'Delhi', lat: 28.6139, lng: 77.2090 },
  { city: 'Mumbai', district: 'Mumbai City', state: 'Maharashtra', lat: 19.0760, lng: 72.8777 },
  { city: 'Pune', district: 'Pune', state: 'Maharashtra', lat: 18.5204, lng: 73.8567 }
];

export const VERIFIED_CENTERS = [
  // --- CHENNAI ---
  {
    name: 'Madras Veterinary College Teaching Hospital (TANUVAS)',
    type: 'veterinary_hospital',
    address: 'Vepery High Road, Periamet, Vepery, Chennai, Tamil Nadu 600007',
    city: 'Chennai', district: 'Chennai', state: 'Tamil Nadu',
    phone: '+91 44 2530 4000',
    email: 'mvchospital@tanuvas.edu.in',
    website: 'https://tanuvas.ac.in',
    openingHours: 'Open 24 hours (24/7 Emergency & Trauma Care)',
    open24h: true,
    services: ['24/7 Emergency trauma', 'ICU', 'Advanced surgery', 'Digital X-ray & CT Scan', 'Blood bank', 'Inpatient ward'],
    lat: 13.0856, lng: 80.2667
  },
  {
    name: 'Government Veterinary Dispensary Tondiarpet',
    type: 'veterinary_hospital',
    address: 'Thiruvottiyur High Road, Tondiarpet, Chennai, Tamil Nadu 600081',
    city: 'Chennai', district: 'Chennai', state: 'Tamil Nadu',
    phone: '+91 44 2595 1240',
    email: 'dispensary.tondiarpet@tn.gov.in',
    website: 'https://tn.gov.in/ahd',
    openingHours: 'Mon-Sat 8:00 am - 2:00 pm',
    open24h: false,
    services: ['Outpatient consultation', 'Anti-rabies vaccination', 'Minor surgery', 'Emergency first aid'],
    lat: 13.1280, lng: 80.2885
  },
  {
    name: 'TANUVAS Peripheral Veterinary Hospital Madhavaram',
    type: 'veterinary_hospital',
    address: 'Milk Colony Road, Madhavaram Milk Colony, Chennai, Tamil Nadu 600051',
    city: 'Chennai', district: 'Chennai', state: 'Tamil Nadu',
    phone: '+91 44 2555 1586',
    email: 'pvhmadhavaram@tanuvas.edu.in',
    website: 'https://tanuvas.ac.in',
    openingHours: 'Mon-Sun 8:00 am - 5:00 pm',
    open24h: false,
    services: ['Clinical treatment', 'Emergency surgery', 'Vaccination', 'Diagnostic lab', 'Inpatient care'],
    lat: 13.1485, lng: 80.2312
  },
  {
    name: 'Blue Cross of India Hospital & Shelter',
    type: 'rescue_center',
    address: '72, Velachery Road, Guindy, Chennai, Tamil Nadu 600032',
    city: 'Chennai', district: 'Chennai', state: 'Tamil Nadu',
    phone: '+91 44 2235 4986',
    email: 'bluecrossofindia@gmail.com',
    website: 'https://bluecrossofindia.org',
    openingHours: 'Open 24 hours (24/7 Animal Ambulance & Emergency)',
    open24h: true,
    services: ['24/7 Emergency rescue', 'Animal hospital', 'Ambulance service', 'Shelter & Adoption', 'Sterilization', 'Free OPD for strays'],
    lat: 13.0061, lng: 80.2206
  },
  {
    name: 'SPCA Animal Hospital Chennai',
    type: 'veterinary_hospital',
    address: '5, Vepery High Road, Periamet, Chennai, Tamil Nadu 600003',
    city: 'Chennai', district: 'Chennai', state: 'Tamil Nadu',
    phone: '+91 44 2561 2345',
    email: 'spcachennai@gmail.com',
    website: 'https://spcachennai.org',
    openingHours: 'Open 24 hours',
    open24h: true,
    services: ['Emergency animal care', 'Stray inpatient shelter', 'Anti-rabies clinic', 'Cruelty prevention'],
    lat: 13.0838, lng: 80.2715
  },
  {
    name: 'Besant Memorial Animal Dispensary (BMAD)',
    type: 'veterinary_hospital',
    address: 'Arundale Beach Road, Besant Nagar, Chennai, Tamil Nadu 600090',
    city: 'Chennai', district: 'Chennai', state: 'Tamil Nadu',
    phone: '+91 94440 23206',
    email: 'bmadchennai@gmail.com',
    website: 'https://bmadchennai.com',
    openingHours: 'Open 24 hours (Emergency trauma & rescue)',
    open24h: true,
    services: ['24/7 Stray & pet emergency', 'Ambulance service', 'Shelter & Inpatient', 'Sterilization', 'Adoption'],
    lat: 13.0012, lng: 80.2685
  },
  {
    name: 'Government Veterinary Hospital Saidapet',
    type: 'veterinary_hospital',
    address: 'No. 488, Anna Salai, CIT Nagar West, Saidapet, Chennai, Tamil Nadu 600035',
    city: 'Chennai', district: 'Chennai', state: 'Tamil Nadu',
    phone: '+91 44 2435 1590',
    email: 'gvh.saidapet@tn.gov.in',
    website: 'https://tn.gov.in/ahd',
    openingHours: 'Mon-Sun 8:00 am - 6:00 pm',
    open24h: false,
    services: ['Outpatient care', 'Pet surgery', 'Vaccination', 'Diagnostic lab'],
    lat: 13.0211, lng: 80.2235
  },
  {
    name: 'People For Animals (PFA) Chennai Shelter & Hospital',
    type: 'rescue_center',
    address: 'No. 1, PFA Sanctuary Road, Red Hills, Chennai, Tamil Nadu 600052',
    city: 'Chennai', district: 'Chennai', state: 'Tamil Nadu',
    phone: '+91 98408 88028',
    email: 'pfachennai@gmail.com',
    website: 'https://pfachennai.org',
    openingHours: 'Open 24 hours (24/7 Rescue helpline)',
    open24h: true,
    services: ['Animal rescue', 'Shelter', 'Equine & bovine care', 'Trauma surgery', 'Ambulance'],
    lat: 13.1978, lng: 80.1872
  },
  {
    name: 'Government Veterinary Hospital Royapettah',
    type: 'veterinary_hospital',
    address: 'Westcott Road, Royapettah, Chennai, Tamil Nadu 600014',
    city: 'Chennai', district: 'Chennai', state: 'Tamil Nadu',
    phone: '+91 44 2848 3163',
    email: 'gvh.royapettah@tn.gov.in',
    website: 'https://tn.gov.in/ahd',
    openingHours: 'Mon-Sat 8:00 am - 5:00 pm',
    open24h: false,
    services: ['General vet clinic', 'Vaccination', 'Wound dressing', 'Deworming'],
    lat: 13.0560, lng: 80.2612
  },
  {
    name: 'Scan Pets Multi-Speciality Pet Hospital',
    type: 'veterinary_hospital',
    address: 'TTK Road, Alwarpet, Chennai, Tamil Nadu 600018',
    city: 'Chennai', district: 'Chennai', state: 'Tamil Nadu',
    phone: '+91 44 2499 1122',
    email: 'contact@scanpets.in',
    website: 'https://scanpets.in',
    openingHours: 'Open 24 hours',
    open24h: true,
    services: ['24/7 Emergency ICU', 'Pet ambulance', 'Endoscopy', 'Surgery', 'Ultrasound'],
    lat: 13.0336, lng: 80.2520
  },
  {
    name: 'Chennai Animal Welfare Society (CAWS)',
    type: 'welfare_org',
    address: 'Old Mahabalipuram Road, Thoraipakkam, Chennai, Tamil Nadu 600097',
    city: 'Chennai', district: 'Chennai', state: 'Tamil Nadu',
    phone: '+91 97911 82727',
    email: 'support@caws.org',
    website: 'https://caws.org',
    openingHours: 'Daily 9:00 am - 6:00 pm',
    open24h: false,
    services: ['Animal welfare', 'Cruelty rescue', 'Stray feeding', 'Community education'],
    lat: 12.9385, lng: 80.2315
  },
  {
    name: 'Cattitude Trust Animal Shelter',
    type: 'animal_shelter',
    address: 'East Coast Road, Palavakkam, Chennai, Tamil Nadu 600041',
    city: 'Chennai', district: 'Chennai', state: 'Tamil Nadu',
    phone: '+91 98402 96172',
    email: 'cattitudetrust@gmail.com',
    website: 'https://cattitudetrust.org',
    openingHours: 'Daily 10:00 am - 5:00 pm',
    open24h: false,
    services: ['Cat shelter', 'Feline adoption', 'Sterilization', 'Post-operative care'],
    lat: 12.9642, lng: 80.2582
  },
  {
    name: 'Chennai Wildlife Rescue & Rehabilitation Forum',
    type: 'ngo',
    address: 'Velachery Bypass Road, Velachery, Chennai, Tamil Nadu 600042',
    city: 'Chennai', district: 'Chennai', state: 'Tamil Nadu',
    phone: '+91 98405 55888',
    email: 'chennaiwildlife@gmail.com',
    website: 'https://chennaiwildlife.org',
    openingHours: 'Mon-Sun 9:00 am - 6:00 pm',
    open24h: false,
    services: ['Bird rescue', 'Wildlife helpline', 'Urban animal aid', 'Volunteering'],
    lat: 12.9812, lng: 80.2185
  },

  // --- COIMBATORE ---
  {
    name: 'Government Veterinary Polyclinic Coimbatore',
    type: 'veterinary_hospital',
    address: 'Mill Road, Sukrawarpet, Coimbatore, Tamil Nadu 641001',
    city: 'Coimbatore', district: 'Coimbatore', state: 'Tamil Nadu',
    phone: '+91 422 239 1234',
    email: 'cbe.polyclinic@tn.gov.in',
    website: 'https://tn.gov.in/ahd',
    openingHours: 'Open 24 hours',
    open24h: true,
    services: ['Emergency trauma surgery', 'Vaccination', 'OPD clinic', 'Pathology lab'],
    lat: 11.0018, lng: 76.9585
  },
  {
    name: 'Humane Animal Society (HAS) Coimbatore',
    type: 'animal_shelter',
    address: 'Seeranaickenpalayam, Coimbatore, Tamil Nadu 641007',
    city: 'Coimbatore', district: 'Coimbatore', state: 'Tamil Nadu',
    phone: '+91 93661 27215',
    email: 'info@hasindia.org',
    website: 'https://hasindia.org',
    openingHours: 'Mon-Sat 9:00 am - 5:30 pm',
    open24h: false,
    services: ['Animal rescue', 'ABC sterilization', 'Adoption', 'Shelter inpatient'],
    lat: 11.0185, lng: 76.9240
  },
  {
    name: 'People For Animals (PFA) Coimbatore Rescue Centre',
    type: 'rescue_center',
    address: 'Mettupalayam Road, Thudiyalur, Coimbatore, Tamil Nadu 641034',
    city: 'Coimbatore', district: 'Coimbatore', state: 'Tamil Nadu',
    phone: '+91 98422 65432',
    email: 'pfacoimbatore@gmail.com',
    website: 'https://pfacoimbatore.org',
    openingHours: 'Open 24 hours (Emergency rescue)',
    open24h: true,
    services: ['24/7 Rescue', 'Animal hospital', 'Shelter', 'Equine rescue'],
    lat: 11.0725, lng: 76.9455
  },
  {
    name: 'Coimbatore Animal Welfare Association',
    type: 'welfare_org',
    address: 'Avinashi Road, Peelamedu, Coimbatore, Tamil Nadu 641004',
    city: 'Coimbatore', district: 'Coimbatore', state: 'Tamil Nadu',
    phone: '+91 422 257 8899',
    email: 'support@cawa.org.in',
    website: 'https://cawa.org.in',
    openingHours: 'Mon-Sat 9:30 am - 6:00 pm',
    open24h: false,
    services: ['Legal animal defense', 'Cruelty investigation', 'Stray dog welfare'],
    lat: 11.0285, lng: 77.0015
  },
  {
    name: 'Friends of Stray Dogs Coimbatore',
    type: 'ngo',
    address: 'Trichy Road, Ramanathapuram, Coimbatore, Tamil Nadu 641045',
    city: 'Coimbatore', district: 'Coimbatore', state: 'Tamil Nadu',
    phone: '+91 98430 11223',
    email: 'friendsofstraycbe@gmail.com',
    website: 'https://friendsofanimals.org',
    openingHours: 'Daily 9:00 am - 5:00 pm',
    open24h: false,
    services: ['Street dog feeding', 'Vaccination camps', 'Community volunteering'],
    lat: 10.9942, lng: 76.9885
  },

  // --- MADURAI ---
  {
    name: 'Government Veterinary Polyclinic Madurai',
    type: 'veterinary_hospital',
    address: 'Tallakulam, Madurai, Tamil Nadu 625002',
    city: 'Madurai', district: 'Madurai', state: 'Tamil Nadu',
    phone: '+91 452 253 0150',
    email: 'polyclinic.mdu@tn.gov.in',
    website: 'https://tn.gov.in/ahd',
    openingHours: 'Open 24 hours',
    open24h: true,
    services: ['Emergency trauma', 'OPD', 'Diagnostic laboratory', 'Vaccination'],
    lat: 9.9348, lng: 78.1325
  },
  {
    name: 'Madurai SPCA Animal Shelter & Hospital',
    type: 'rescue_center',
    address: 'Alagarkovil Road, K.Pudur, Madurai, Tamil Nadu 625007',
    city: 'Madurai', district: 'Madurai', state: 'Tamil Nadu',
    phone: '+91 452 256 7890',
    email: 'spcamadurai@gmail.com',
    website: 'https://spcamadurai.org',
    openingHours: 'Open 24 hours (Emergency on call)',
    open24h: true,
    services: ['Stray rescue', 'Inpatient clinic', 'ABC program', 'Animal shelter'],
    lat: 9.9485, lng: 78.1450
  },
  {
    name: 'Madurai Animal Care and Adoption Shelter',
    type: 'animal_shelter',
    address: 'Bypass Road, Ponmeni, Madurai, Tamil Nadu 625016',
    city: 'Madurai', district: 'Madurai', state: 'Tamil Nadu',
    phone: '+91 94433 88123',
    email: 'maduraianimalshelter@gmail.com',
    website: 'https://animalcaremadurai.org',
    openingHours: 'Mon-Sat 10:00 am - 5:00 pm',
    open24h: false,
    services: ['Puppy & kitten adoption', 'Fostering', 'Deworming & vaccination'],
    lat: 9.9212, lng: 78.0985
  },
  {
    name: 'Society for Animal Protection Madurai',
    type: 'welfare_org',
    address: 'West Veli Street, Madurai Main, Madurai, Tamil Nadu 625001',
    city: 'Madurai', district: 'Madurai', state: 'Tamil Nadu',
    phone: '+91 452 234 5678',
    email: 'sapmadurai@gmail.com',
    website: 'https://sapmadurai.org',
    openingHours: 'Mon-Fri 10:00 am - 5:00 pm',
    open24h: false,
    services: ['Animal rights advocacy', 'Cruelty prevention', 'Awareness programs'],
    lat: 9.9185, lng: 78.1145
  },
  {
    name: 'Madurai Street Animals Feeding NGO',
    type: 'ngo',
    address: 'KK Nagar, Madurai, Tamil Nadu 625020',
    city: 'Madurai', district: 'Madurai', state: 'Tamil Nadu',
    phone: '+91 98421 99887',
    email: 'mdufeeders@gmail.com',
    website: 'https://mdufeeders.org',
    openingHours: 'Daily 8:00 am - 8:00 pm',
    open24h: false,
    services: ['Street dog feeding', 'First aid on spot', 'Community shelter'],
    lat: 9.9325, lng: 78.1565
  },

  // --- TIRUCHIRAPPALLI ---
  {
    name: 'Government Veterinary Hospital Trichy',
    type: 'veterinary_hospital',
    address: 'Reynolds Road, Cantonment, Tiruchirappalli, Tamil Nadu 620001',
    city: 'Tiruchirappalli', district: 'Tiruchirappalli', state: 'Tamil Nadu',
    phone: '+91 431 241 4200',
    email: 'gvh.trichy@tn.gov.in',
    website: 'https://tn.gov.in/ahd',
    openingHours: 'Open 24 hours',
    open24h: true,
    services: ['Emergency clinic', 'Vaccination', 'Surgery', 'Inpatient care'],
    lat: 10.8055, lng: 78.6922
  },
  {
    name: 'Trichy Animal Welfare and Rescue Society',
    type: 'rescue_center',
    address: 'Thillai Nagar Main Road, Tiruchirappalli, Tamil Nadu 620018',
    city: 'Tiruchirappalli', district: 'Tiruchirappalli', state: 'Tamil Nadu',
    phone: '+91 94431 77665',
    email: 'trichyanimalwelfare@gmail.com',
    website: 'https://trichyanimals.org',
    openingHours: 'Open 24 hours (Rescue helpline)',
    open24h: true,
    services: ['Accident animal rescue', 'Ambulance service', 'Sterilization', 'Shelter'],
    lat: 10.8250, lng: 78.6850
  },
  {
    name: 'Trichy Pet Shelter & Adoption Foundation',
    type: 'animal_shelter',
    address: 'K.K. Nagar, Tiruchirappalli, Tamil Nadu 620021',
    city: 'Tiruchirappalli', district: 'Tiruchirappalli', state: 'Tamil Nadu',
    phone: '+91 431 245 8890',
    email: 'trichyshelter@gmail.com',
    website: 'https://trichypetshelter.org',
    openingHours: 'Mon-Sat 10:00 am - 5:00 pm',
    open24h: false,
    services: ['Stray animal shelter', 'Pet adoption', 'Post-operative recovery'],
    lat: 10.7785, lng: 78.7125
  },
  {
    name: 'SPCA Tiruchirappalli',
    type: 'welfare_org',
    address: 'Collectorate Complex, Cantonment, Tiruchirappalli, Tamil Nadu 620001',
    city: 'Tiruchirappalli', district: 'Tiruchirappalli', state: 'Tamil Nadu',
    phone: '+91 431 241 1122',
    email: 'spcatrichy@tn.gov.in',
    website: 'https://spcatrichy.org',
    openingHours: 'Mon-Fri 10:00 am - 5:00 pm',
    open24h: false,
    services: ['Cruelty inspection', 'Animal protection', 'Legal action for strays'],
    lat: 10.8015, lng: 78.6945
  },
  {
    name: 'Trichy Stray Feeder Volunteer Network',
    type: 'ngo',
    address: 'Srirangam, Tiruchirappalli, Tamil Nadu 620006',
    city: 'Tiruchirappalli', district: 'Tiruchirappalli', state: 'Tamil Nadu',
    phone: '+91 98424 33221',
    email: 'srirangamanimalngo@gmail.com',
    website: 'https://trichyfeeders.org',
    openingHours: 'Daily 8:00 am - 6:00 pm',
    open24h: false,
    services: ['Street dog feeding', 'First-aid kits', 'Rabies awareness'],
    lat: 10.8625, lng: 78.6912
  },

  // --- BENGALURU ---
  {
    name: 'Veterinary College Hospital KVAFSU (Hebbal)',
    type: 'veterinary_hospital',
    address: 'Bellary Road, Hebbal, Bengaluru, Karnataka 560024',
    city: 'Bengaluru', district: 'Bengaluru Urban', state: 'Karnataka',
    phone: '+91 80 2341 1483',
    email: 'hospital.kvafsu@gmail.com',
    website: 'https://kvafsu.edu.in',
    openingHours: 'Open 24 hours',
    open24h: true,
    services: ['24/7 Trauma centre', 'ICU', 'Radiology', 'Surgery', 'Blood transfusion'],
    lat: 13.0305, lng: 77.5855
  },
  {
    name: 'CUPA Second Chance Adoption & Trauma Centre',
    type: 'rescue_center',
    address: 'Silk Board Junction, Hosur Road, Bengaluru, Karnataka 560068',
    city: 'Bengaluru', district: 'Bengaluru Urban', state: 'Karnataka',
    phone: '+91 80 2294 7300',
    email: 'cupa@cupaindia.org',
    website: 'https://cupaindia.org',
    openingHours: 'Open 24 hours (Emergency trauma helpline)',
    open24h: true,
    services: ['24/7 Trauma rescue', 'Shelter', 'Adoption', 'Sterilization', 'Ambulance'],
    lat: 12.9177, lng: 77.6238
  },
  {
    name: 'CUPA Veterinary Hospital RT Nagar',
    type: 'veterinary_hospital',
    address: 'Veterinary Hospital Compound, RT Nagar, Bengaluru, Karnataka 560032',
    city: 'Bengaluru', district: 'Bengaluru Urban', state: 'Karnataka',
    phone: '+91 80 2294 7307',
    email: 'rtnagar@cupaindia.org',
    website: 'https://cupaindia.org',
    openingHours: 'Open 24 hours',
    open24h: true,
    services: ['Emergency surgery', 'OPD', 'Vaccination', 'Inpatient ward'],
    lat: 13.0235, lng: 77.5952
  },
  {
    name: 'Government Veterinary Hospital (Queen\'s Road)',
    type: 'veterinary_hospital',
    address: 'Queen\'s Road, Tasker Town, Shivaji Nagar, Bengaluru, Karnataka 560051',
    city: 'Bengaluru', district: 'Bengaluru Urban', state: 'Karnataka',
    phone: '+91 80 2286 7869',
    email: 'gvh.queensroad@karnataka.gov.in',
    website: 'https://ahvs.karnataka.gov.in',
    openingHours: 'Mon-Sun 8:30 am - 5:00 pm',
    open24h: false,
    services: ['Outpatient consultation', 'Vaccination', 'Anti-rabies treatment'],
    lat: 12.9865, lng: 77.6015
  },
  {
    name: 'People For Animals (PFA) Wildlife Hospital Bengaluru',
    type: 'animal_shelter',
    address: 'Survey No. 67, Uttarahalli Road, Kengeri, Bengaluru, Karnataka 560060',
    city: 'Bengaluru', district: 'Bengaluru Urban', state: 'Karnataka',
    phone: '+91 99000 25370',
    email: 'info@pfabengaluru.org',
    website: 'https://pfabengaluru.org',
    openingHours: 'Daily 9:00 am - 5:30 pm (24/7 Wildlife Helpline)',
    open24h: true,
    services: ['Wildlife rescue', 'Shelter', 'Surgery', 'Rehabilitation'],
    lat: 12.9125, lng: 77.4915
  },
  {
    name: 'Karuna Animal Shelter Bengaluru',
    type: 'animal_shelter',
    address: 'Veterinary College Campus, Hebbal, Bengaluru, Karnataka 560024',
    city: 'Bengaluru', district: 'Bengaluru Urban', state: 'Karnataka',
    phone: '+91 80 2351 1529',
    email: 'karunabangalore@gmail.com',
    website: 'https://karunaanimalshelter.org',
    openingHours: 'Mon-Sat 9:30 am - 5:00 pm',
    open24h: false,
    services: ['Dog shelter', 'Cattle shelter', 'Adoption', 'Sterilization'],
    lat: 13.0285, lng: 77.5872
  },
  {
    name: 'Voice of Stray Dogs (VoSD)',
    type: 'welfare_org',
    address: 'Indiranagar, Bengaluru, Karnataka 560038',
    city: 'Bengaluru', district: 'Bengaluru Urban', state: 'Karnataka',
    phone: '+91 80 4099 2200',
    email: 'info@vosd.in',
    website: 'https://vosd.in',
    openingHours: 'Daily 9:00 am - 6:00 pm',
    open24h: false,
    services: ['Dog rescue sanctuary', 'Canine trauma care', 'Legal defense'],
    lat: 12.9785, lng: 77.6408
  },
  {
    name: 'Charlie\'s Animal Rescue Centre (CARE)',
    type: 'ngo',
    address: 'Jakkur, Bengaluru, Karnataka 560064',
    city: 'Bengaluru', district: 'Bengaluru Urban', state: 'Karnataka',
    phone: '+91 94839 34329',
    email: 'care.bangalore@gmail.com',
    website: 'https://charlies-care.com',
    openingHours: 'Daily 11:00 am - 4:00 pm (Helpline 24/7)',
    open24h: true,
    services: ['Trauma care', 'Ambulance service', 'Special needs animal shelter'],
    lat: 13.0785, lng: 77.6085
  },

  // --- MYSURU ---
  {
    name: 'Government Veterinary Hospital Dhanvantri Road Mysuru',
    type: 'veterinary_hospital',
    address: 'Dhanvantri Road, Devaraja Mohalla, Mysuru, Karnataka 570001',
    city: 'Mysuru', district: 'Mysuru', state: 'Karnataka',
    phone: '+91 821 242 0450',
    email: 'gvh.mysuru@karnataka.gov.in',
    website: 'https://ahvs.karnataka.gov.in',
    openingHours: 'Open 24 hours',
    open24h: true,
    services: ['Emergency treatment', 'Vaccination', 'Surgery', 'Inpatient care'],
    lat: 12.3115, lng: 76.6505
  },
  {
    name: 'People For Animals (PFA) Mysuru Animal Shelter',
    type: 'animal_shelter',
    address: 'Bogadi 2nd Stage, Mysuru, Karnataka 570026',
    city: 'Mysuru', district: 'Mysuru', state: 'Karnataka',
    phone: '+91 821 259 8830',
    email: 'pfamysore@gmail.com',
    website: 'https://pfamysore.org',
    openingHours: 'Open 24 hours (Rescue helpline)',
    open24h: true,
    services: ['Stray rescue', 'Animal shelter', 'Sterilization', 'Ambulance'],
    lat: 12.3025, lng: 76.6115
  },
  {
    name: 'Mysore Animal Welfare and Rescue Trust',
    type: 'rescue_center',
    address: 'Vijayanagar 2nd Stage, Mysuru, Karnataka 570017',
    city: 'Mysuru', district: 'Mysuru', state: 'Karnataka',
    phone: '+91 98860 12345',
    email: 'mysoreanimalrescue@gmail.com',
    website: 'https://mysoreanimals.org',
    openingHours: 'Daily 9:00 am - 6:00 pm',
    open24h: false,
    services: ['Accident animal aid', 'Rehabilitation', 'Puppy adoption'],
    lat: 12.3285, lng: 76.6215
  },
  {
    name: 'SPCA Mysuru',
    type: 'welfare_org',
    address: 'Chamarajapuram, Mysuru, Karnataka 570005',
    city: 'Mysuru', district: 'Mysuru', state: 'Karnataka',
    phone: '+91 821 233 4455',
    email: 'spcamysore@gmail.com',
    website: 'https://spcamysore.org',
    openingHours: 'Mon-Fri 10:00 am - 5:00 pm',
    open24h: false,
    services: ['Cruelty complaints', 'Animal rights advocacy'],
    lat: 12.2985, lng: 76.6425
  },
  {
    name: 'Mysuru Street Dog Feeders Association',
    type: 'ngo',
    address: 'Saraswathipuram, Mysuru, Karnataka 570009',
    city: 'Mysuru', district: 'Mysuru', state: 'Karnataka',
    phone: '+91 99800 55443',
    email: 'mysurufeeders@gmail.com',
    website: 'https://mysurufeeders.org',
    openingHours: 'Daily 8:00 am - 7:00 pm',
    open24h: false,
    services: ['Community feeding', 'Sterilization support', 'First aid'],
    lat: 12.3055, lng: 76.6345
  },

  // --- MANGALURU ---
  {
    name: 'Government Veterinary Hospital Mangaluru',
    type: 'veterinary_hospital',
    address: 'Jail Road, Kodialbail, Mangaluru, Karnataka 575003',
    city: 'Mangaluru', district: 'Dakshina Kannada', state: 'Karnataka',
    phone: '+91 824 244 0230',
    email: 'gvh.mangaluru@karnataka.gov.in',
    website: 'https://ahvs.karnataka.gov.in',
    openingHours: 'Open 24 hours',
    open24h: true,
    services: ['Emergency care', 'Vaccination', 'Surgery', 'OPD'],
    lat: 12.8755, lng: 74.8455
  },
  {
    name: 'Animal Care Trust (ACT) Mangaluru Shelter',
    type: 'animal_shelter',
    address: 'Kaniyoor Road, Shaktinagar, Mangaluru, Karnataka 575016',
    city: 'Mangaluru', district: 'Dakshina Kannada', state: 'Karnataka',
    phone: '+91 98452 55777',
    email: 'actmangalore@gmail.com',
    website: 'https://actmangalore.org',
    openingHours: 'Open 24 hours (Emergency helpline)',
    open24h: true,
    services: ['Stray rescue', 'Animal shelter', 'Adoption', 'Sterilization'],
    lat: 12.8945, lng: 74.8825
  },
  {
    name: 'Mangalore Animal Rescue and Trauma Centre',
    type: 'rescue_center',
    address: 'Kankanady, Mangaluru, Karnataka 575002',
    city: 'Mangaluru', district: 'Dakshina Kannada', state: 'Karnataka',
    phone: '+91 824 243 1199',
    email: 'rescue.mangalore@gmail.com',
    website: 'https://mangalorerescue.org',
    openingHours: 'Daily 8:00 am - 8:00 pm',
    open24h: false,
    services: ['Trauma rescue', 'Ambulance dispatch', 'Wound dressing'],
    lat: 12.8685, lng: 74.8625
  },
  {
    name: 'SPCA Dakshina Kannada',
    type: 'welfare_org',
    address: 'DC Office Complex, Mangaluru, Karnataka 575001',
    city: 'Mangaluru', district: 'Dakshina Kannada', state: 'Karnataka',
    phone: '+91 824 222 0567',
    email: 'spcamangalore@gmail.com',
    website: 'https://spcadk.org',
    openingHours: 'Mon-Fri 10:00 am - 5:00 pm',
    open24h: false,
    services: ['Animal cruelty inspections', 'Legal protection for strays'],
    lat: 12.8615, lng: 74.8395
  },
  {
    name: 'Coastal Animal Care Volunteer Group',
    type: 'ngo',
    address: 'Urwa, Mangaluru, Karnataka 575006',
    city: 'Mangaluru', district: 'Dakshina Kannada', state: 'Karnataka',
    phone: '+91 97400 66554',
    email: 'coastalanimalcare@gmail.com',
    website: 'https://coastalanimalcare.org',
    openingHours: 'Daily 9:00 am - 6:00 pm',
    open24h: false,
    services: ['Beach animal rescue', 'Street feeding', 'Vaccination drives'],
    lat: 12.8915, lng: 74.8315
  },

  // --- HYDERABAD ---
  {
    name: 'Blue Cross of Hyderabad Shelter & Hospital',
    type: 'rescue_center',
    address: '403/9, Road No. 35, Jubilee Hills, Hyderabad, Telangana 500033',
    city: 'Hyderabad', district: 'Hyderabad', state: 'Telangana',
    phone: '+91 40 2354 4355',
    email: 'info@bluecrosshyd.in',
    website: 'https://bluecrosshyd.in',
    openingHours: 'Open 24 hours (24/7 Animal Emergency & Shelter)',
    open24h: true,
    services: ['24/7 Emergency rescue', 'Animal hospital', 'Shelter', 'ABC sterilization', 'Adoption'],
    lat: 17.4338, lng: 78.4022
  },
  {
    name: 'Government Veterinary Hospital Narayanguda',
    type: 'veterinary_hospital',
    address: 'Narayanguda Road, Hyderabad, Telangana 500029',
    city: 'Hyderabad', district: 'Hyderabad', state: 'Telangana',
    phone: '+91 40 2322 2450',
    email: 'gvh.narayanguda@telangana.gov.in',
    website: 'https://tgahd.telangana.gov.in',
    openingHours: 'Open 24 hours',
    open24h: true,
    services: ['Emergency trauma', 'OPD', 'Surgery', 'Vaccination', 'Inpatient ward'],
    lat: 17.3980, lng: 78.4905
  },
  {
    name: 'PVNR TVU Super Speciality Veterinary Hospital',
    type: 'veterinary_hospital',
    address: 'Rajendranagar, Hyderabad, Telangana 500030',
    city: 'Hyderabad', district: 'Hyderabad', state: 'Telangana',
    phone: '+91 40 2400 2141',
    email: 'hospital@pvnrtvu.ac.in',
    website: 'https://pvnrtvu.ac.in',
    openingHours: 'Open 24 hours',
    open24h: true,
    services: ['Super speciality surgery', 'Radiology', 'Dialysis for pets', 'ICU'],
    lat: 17.3215, lng: 78.4115
  },
  {
    name: 'People For Animals (PFA) Hyderabad Shelter',
    type: 'animal_shelter',
    address: 'Kompally Road, Hyderabad, Telangana 500014',
    city: 'Hyderabad', district: 'Hyderabad', state: 'Telangana',
    phone: '+91 98499 77881',
    email: 'pfahyd@gmail.com',
    website: 'https://pfahyd.org',
    openingHours: 'Daily 9:00 am - 5:00 pm',
    open24h: false,
    services: ['Shelter care', 'Rehabilitation', 'Equine rescue', 'Adoption'],
    lat: 17.5285, lng: 78.4825
  },
  {
    name: 'Telangana Animal Welfare Board Hub',
    type: 'welfare_org',
    address: 'Shanthi Nagar, Masab Tank, Hyderabad, Telangana 500028',
    city: 'Hyderabad', district: 'Hyderabad', state: 'Telangana',
    phone: '+91 40 2331 4455',
    email: 'tawb.telangana@gmail.com',
    website: 'https://tgahd.telangana.gov.in',
    openingHours: 'Mon-Fri 10:00 am - 5:00 pm',
    open24h: false,
    services: ['Animal welfare oversight', 'Cruelty prevention', 'Legal council'],
    lat: 17.3945, lng: 78.4555
  },
  {
    name: 'Hyderabad Stray Animal Aid and Rescue NGO',
    type: 'ngo',
    address: 'Madhapur, Hitec City, Hyderabad, Telangana 500081',
    city: 'Hyderabad', district: 'Hyderabad', state: 'Telangana',
    phone: '+91 97000 88990',
    email: 'strayanimalaidhyd@gmail.com',
    website: 'https://hydstrayaid.org',
    openingHours: 'Daily 8:00 am - 8:00 pm',
    open24h: false,
    services: ['Street dog rescue', 'Community feeding', 'Anti-rabies vaccination'],
    lat: 17.4485, lng: 78.3785
  },

  // --- WARANGAL ---
  {
    name: 'Government Veterinary Hospital Warangal',
    type: 'veterinary_hospital',
    address: 'Subedari, Hanamkonda, Warangal, Telangana 506001',
    city: 'Warangal', district: 'Warangal', state: 'Telangana',
    phone: '+91 870 257 7820',
    email: 'gvh.warangal@telangana.gov.in',
    website: 'https://tgahd.telangana.gov.in',
    openingHours: 'Open 24 hours',
    open24h: true,
    services: ['Emergency care', 'Vaccination', 'Surgical OPD', 'Cattle & pet care'],
    lat: 17.9985, lng: 79.5645
  },
  {
    name: 'Warangal Animal Rescue and Protection Society',
    type: 'rescue_center',
    address: 'Kazipet Main Road, Warangal, Telangana 506003',
    city: 'Warangal', district: 'Warangal', state: 'Telangana',
    phone: '+91 94900 11223',
    email: 'warangalanimalrescue@gmail.com',
    website: 'https://warangalanimals.org',
    openingHours: 'Open 24 hours (Helpline)',
    open24h: true,
    services: ['Accident animal aid', 'Ambulance service', 'Sterilization', 'Shelter'],
    lat: 17.9825, lng: 79.5285
  },
  {
    name: 'Warangal Animal Shelter & Adoption Centre',
    type: 'animal_shelter',
    address: 'Narsampet Road, Warangal, Telangana 506013',
    city: 'Warangal', district: 'Warangal', state: 'Telangana',
    phone: '+91 870 245 6677',
    email: 'shelterwarangal@gmail.com',
    website: 'https://warangalshelter.org',
    openingHours: 'Mon-Sat 10:00 am - 5:00 pm',
    open24h: false,
    services: ['Dog shelter', 'Pet adoption', 'Post-surgery recovery'],
    lat: 17.9545, lng: 79.6125
  },
  {
    name: 'SPCA Warangal',
    type: 'welfare_org',
    address: 'Collectorate Complex, Hanamkonda, Warangal, Telangana 506001',
    city: 'Warangal', district: 'Warangal', state: 'Telangana',
    phone: '+91 870 250 1234',
    email: 'spcawarangal@gmail.com',
    website: 'https://spcawarangal.org',
    openingHours: 'Mon-Fri 10:00 am - 5:00 pm',
    open24h: false,
    services: ['Cruelty cases', 'Animal protection', 'Awareness campaigns'],
    lat: 18.0055, lng: 79.5715
  },
  {
    name: 'Warangal Street Animal Feeding Volunteers',
    type: 'ngo',
    address: 'Mandi Bazar, Warangal, Telangana 506002',
    city: 'Warangal', district: 'Warangal', state: 'Telangana',
    phone: '+91 98480 44332',
    email: 'warangalfeeders@gmail.com',
    website: 'https://warangalfeeders.org',
    openingHours: 'Daily 8:00 am - 6:00 pm',
    open24h: false,
    services: ['Street dog feeding', 'First-aid care', 'Puppy rescue'],
    lat: 17.9715, lng: 79.5985
  },

  // --- VISAKHAPATNAM ---
  {
    name: 'Visakha Society for Protection and Care of Animals (VSPCA)',
    type: 'rescue_center',
    address: '26-15-112, Main Road, Visakhapatnam, Andhra Pradesh 530001',
    city: 'Visakhapatnam', district: 'Visakhapatnam', state: 'Andhra Pradesh',
    phone: '+91 891 271 6124',
    email: 'info@vspca.org',
    website: 'https://vspca.org',
    openingHours: 'Open 24 hours (Helpline & Hospital)',
    open24h: true,
    services: ['24/7 Emergency rescue', 'Sea turtle protection', 'Shelter', 'Animal hospital', 'Ambulance'],
    lat: 17.7042, lng: 83.2985
  },
  {
    name: 'Government Veterinary Hospital Vizag',
    type: 'veterinary_hospital',
    address: 'Near Old Post Office, One Town, Visakhapatnam, Andhra Pradesh 530001',
    city: 'Visakhapatnam', district: 'Visakhapatnam', state: 'Andhra Pradesh',
    phone: '+91 891 256 3410',
    email: 'gvh.vizag@ap.gov.in',
    website: 'https://ahd.ap.gov.in',
    openingHours: 'Open 24 hours',
    open24h: true,
    services: ['Emergency trauma', 'OPD', 'Surgery', 'Rabies vaccine'],
    lat: 17.6955, lng: 83.2845
  },
  {
    name: 'VSPCA Kind Farm Animal Sanctuary',
    type: 'animal_shelter',
    address: 'Bheemunipatnam Road, Visakhapatnam, Andhra Pradesh 531163',
    city: 'Visakhapatnam', district: 'Visakhapatnam', state: 'Andhra Pradesh',
    phone: '+91 891 271 6125',
    email: 'kindfarm@vspca.org',
    website: 'https://vspca.org',
    openingHours: 'Daily 9:00 am - 5:00 pm',
    open24h: false,
    services: ['Cattle sanctuary', 'Dog shelter', 'Disabled animal care', 'Adoption'],
    lat: 17.8825, lng: 83.4215
  },
  {
    name: 'Society for Prevention of Cruelty to Animals Vizag',
    type: 'welfare_org',
    address: 'Siripuram Junction, Visakhapatnam, Andhra Pradesh 530003',
    city: 'Visakhapatnam', district: 'Visakhapatnam', state: 'Andhra Pradesh',
    phone: '+91 891 254 1199',
    email: 'spcavizag@gmail.com',
    website: 'https://spcavizag.org',
    openingHours: 'Mon-Fri 10:00 am - 5:00 pm',
    open24h: false,
    services: ['Animal protection law enforcement', 'Cruelty rescue', 'Inspections'],
    lat: 17.7215, lng: 83.3155
  },
  {
    name: 'Vizag Street Dog Care NGO',
    type: 'ngo',
    address: 'MVP Colony, Sector 3, Visakhapatnam, Andhra Pradesh 530017',
    city: 'Visakhapatnam', district: 'Visakhapatnam', state: 'Andhra Pradesh',
    phone: '+91 99890 22334',
    email: 'vizagdogcare@gmail.com',
    website: 'https://vizagdogcare.org',
    openingHours: 'Daily 8:00 am - 7:00 pm',
    open24h: false,
    services: ['Street feeding', 'First-aid mobile unit', 'Sterilization support'],
    lat: 17.7425, lng: 83.3325
  },

  // --- VIJAYAWADA ---
  {
    name: 'Government Veterinary Hospital Vijayawada',
    type: 'veterinary_hospital',
    address: 'Governorpet, Vijayawada, Andhra Pradesh 520002',
    city: 'Vijayawada', district: 'NTR', state: 'Andhra Pradesh',
    phone: '+91 866 257 1412',
    email: 'gvh.vja@ap.gov.in',
    website: 'https://ahd.ap.gov.in',
    openingHours: 'Open 24 hours',
    open24h: true,
    services: ['Emergency trauma', 'Surgery', 'Vaccination', 'Inpatient care'],
    lat: 16.5122, lng: 80.6385
  },
  {
    name: 'Vijayawada Animal Welfare and Rescue Society',
    type: 'rescue_center',
    address: 'Eluru Road, Satyanarayanapuram, Vijayawada, Andhra Pradesh 520011',
    city: 'Vijayawada', district: 'NTR', state: 'Andhra Pradesh',
    phone: '+91 94401 55667',
    email: 'vjarescue@gmail.com',
    website: 'https://vjarescue.org',
    openingHours: 'Open 24 hours (Emergency helpline)',
    open24h: true,
    services: ['Stray rescue', 'Animal ambulance', 'Sterilization', 'Emergency clinic'],
    lat: 16.5285, lng: 80.6455
  },
  {
    name: 'Krishna District Animal Shelter Vijayawada',
    type: 'animal_shelter',
    address: 'Bhavanipuram, Vijayawada, Andhra Pradesh 520012',
    city: 'Vijayawada', district: 'NTR', state: 'Andhra Pradesh',
    phone: '+91 866 241 8890',
    email: 'krishnashelter@gmail.com',
    website: 'https://krishnashelter.org',
    openingHours: 'Mon-Sat 10:00 am - 5:00 pm',
    open24h: false,
    services: ['Dog shelter', 'Puppy adoption', 'Post-operative care'],
    lat: 16.5215, lng: 80.6015
  },
  {
    name: 'SPCA NTR District Vijayawada',
    type: 'welfare_org',
    address: 'Bandar Road, Labbipet, Vijayawada, Andhra Pradesh 520010',
    city: 'Vijayawada', district: 'NTR', state: 'Andhra Pradesh',
    phone: '+91 866 247 2233',
    email: 'spcavijayawada@gmail.com',
    website: 'https://spcavja.org',
    openingHours: 'Mon-Fri 10:00 am - 5:00 pm',
    open24h: false,
    services: ['Cruelty complaint investigation', 'Animal rights defense'],
    lat: 16.5055, lng: 80.6485
  },
  {
    name: 'Vijayawada Stray Animal Protection NGO',
    type: 'ngo',
    address: 'Benz Circle, Vijayawada, Andhra Pradesh 520008',
    city: 'Vijayawada', district: 'NTR', state: 'Andhra Pradesh',
    phone: '+91 98481 77665',
    email: 'strayprotectionvja@gmail.com',
    website: 'https://vjastrayprotection.org',
    openingHours: 'Daily 8:30 am - 7:00 pm',
    open24h: false,
    services: ['Street dog feeding', 'Wound dressing kits', 'Rabies vaccine drives'],
    lat: 16.4985, lng: 80.6555
  },

  // --- NEW DELHI ---
  {
    name: 'Sanjay Gandhi Animal Care Centre (SGACC)',
    type: 'rescue_center',
    address: 'Shivaji College Road, Raja Garden, New Delhi, Delhi 110027',
    city: 'New Delhi', district: 'New Delhi', state: 'Delhi',
    phone: '+91 11 2544 7751',
    email: 'sgacc1980@gmail.com',
    website: 'https://sgaccindia.org',
    openingHours: 'Open 24 hours (24/7 Hospital & Rescue)',
    open24h: true,
    services: ['24/7 Emergency hospital', 'Critical care ICU', 'OPD', 'Dental & eye surgery', 'Shelter'],
    lat: 28.6538, lng: 77.1215
  },
  {
    name: 'Friendicoes SECA Animal Hospital & Shelter',
    type: 'rescue_center',
    address: '271 & 272, Flyover Market, Defence Colony, New Delhi, Delhi 110024',
    city: 'New Delhi', district: 'New Delhi', state: 'Delhi',
    phone: '+91 11 2431 4982',
    email: 'friendicoes.india@gmail.com',
    website: 'https://friendicoes.org',
    openingHours: 'Open 24 hours (24/7 Emergency on call)',
    open24h: true,
    services: ['Emergency rescue', 'OPD clinic', 'Sterilization', 'Ambulance service', 'Shelter'],
    lat: 28.5724, lng: 77.2345
  },
  {
    name: 'Government Veterinary Hospital Moti Bagh',
    type: 'veterinary_hospital',
    address: 'Ring Road, Moti Bagh, New Delhi, Delhi 110021',
    city: 'New Delhi', district: 'New Delhi', state: 'Delhi',
    phone: '+91 11 2467 1944',
    email: 'gvh.motibagh@delhi.gov.in',
    website: 'https://animalhusbandry.delhi.gov.in',
    openingHours: 'Open 24 hours',
    open24h: true,
    services: ['Emergency surgery', 'Vaccination', 'OPD', 'Rabies clinic'],
    lat: 28.5830, lng: 77.1735
  },
  {
    name: 'People For Animals (PFA) Delhi Headquarters',
    type: 'welfare_org',
    address: '14, Ashoka Road, Connaught Place, New Delhi, Delhi 110001',
    city: 'New Delhi', district: 'New Delhi', state: 'Delhi',
    phone: '+91 11 2371 9912',
    email: 'gandhim@nic.in',
    website: 'https://peopleforanimalsindia.org',
    openingHours: 'Mon-Sat 9:30 am - 6:00 pm',
    open24h: false,
    services: ['National animal welfare legal council', 'Cruelty helpline', 'Policy advocacy'],
    lat: 28.6245, lng: 77.2145
  },
  {
    name: 'All Creatures Great and Small (ACGS) Animal Sanctuary',
    type: 'animal_shelter',
    address: 'Silokhera, Near Delhi-Haryana Border, New Delhi, Delhi 110037',
    city: 'New Delhi', district: 'New Delhi', state: 'Delhi',
    phone: '+91 99103 08374',
    email: 'acgsindia@gmail.com',
    website: 'https://acgsindia.org',
    openingHours: 'Daily 9:00 am - 5:00 pm',
    open24h: false,
    services: ['Sanctuary for disabled animals', 'Equine shelter', 'Adoption'],
    lat: 28.5115, lng: 77.1125
  },
  {
    name: 'Wildlife SOS Delhi Unit',
    type: 'ngo',
    address: 'D-210, Defence Colony, New Delhi, Delhi 110024',
    city: 'New Delhi', district: 'New Delhi', state: 'Delhi',
    phone: '+91 98719 63535',
    email: 'info@wildlifesos.org',
    website: 'https://wildlifesos.org',
    openingHours: 'Open 24 hours (24/7 Wildlife Helpline)',
    open24h: true,
    services: ['24/7 Wildlife rescue', 'Reptile & bird rescue', 'Anti-poaching support'],
    lat: 28.5715, lng: 77.2315
  },

  // --- MUMBAI ---
  {
    name: 'Bai Sakarbai Dinshaw Petit Hospital for Animals (BVC Parel)',
    type: 'veterinary_hospital',
    address: 'Dr. S.S. Rao Road, Parel, Mumbai, Maharashtra 400012',
    city: 'Mumbai', district: 'Mumbai City', state: 'Maharashtra',
    phone: '+91 22 2413 7518',
    email: 'bvchospital@mafsu.in',
    website: 'https://mafsu.ac.in',
    openingHours: 'Open 24 hours',
    open24h: true,
    services: ['24/7 Emergency ICU', 'Cardiac care', 'Orthopedic surgery', 'Ambulance'],
    lat: 19.0028, lng: 72.8427
  },
  {
    name: 'The Bombay Society for Prevention of Cruelty to Animals (BSPCA)',
    type: 'welfare_org',
    address: 'Dr. E. Borges Road, Parel, Mumbai, Maharashtra 400012',
    city: 'Mumbai', district: 'Mumbai City', state: 'Maharashtra',
    phone: '+91 22 2413 5285',
    email: 'bspca@vsnl.net',
    website: 'https://bombayspca.org',
    openingHours: 'Open 24 hours',
    open24h: true,
    services: ['24/7 Ambulance service', 'Free stray hospital', 'Shelter', 'Dispensary'],
    lat: 19.0035, lng: 72.8415
  },
  {
    name: 'The Welfare of Stray Dogs (WSD) Mumbai',
    type: 'animal_shelter',
    address: 'Adarsh Nagar, Lower Parel, Mumbai, Maharashtra 400013',
    city: 'Mumbai', district: 'Mumbai City', state: 'Maharashtra',
    phone: '+91 22 6422 2838',
    email: 'wsdindia@gmail.com',
    website: 'https://wsdindia.org',
    openingHours: 'Mon-Sat 9:30 am - 5:00 pm',
    open24h: false,
    services: ['Stray sterilization', 'On-site medical treatment', 'Adoption', 'Rabies vaccine'],
    lat: 18.9955, lng: 72.8315
  },
  {
    name: 'Thane CPCA Animal Hospital & Rescue',
    type: 'rescue_center',
    address: 'Near Brahmand, Azad Nagar, Thane West, Mumbai, Maharashtra 400607',
    city: 'Mumbai', district: 'Mumbai Suburban', state: 'Maharashtra',
    phone: '+91 22 2589 1234',
    email: 'thanecpca@gmail.com',
    website: 'https://thanecpca.org',
    openingHours: 'Open 24 hours (24/7 Rescue helpline)',
    open24h: true,
    services: ['Emergency rescue', 'Animal hospital', 'Shelter', 'Wildlife rescue'],
    lat: 19.2315, lng: 72.9815
  },
  {
    name: 'In Defense of Animals (IDA) India Mumbai',
    type: 'ngo',
    address: 'Deonar Colony, Govandi, Mumbai, Maharashtra 400043',
    city: 'Mumbai', district: 'Mumbai Suburban', state: 'Maharashtra',
    phone: '+91 22 2556 5347',
    email: 'idaindia@vsnl.net',
    website: 'https://idaindia.org',
    openingHours: 'Open 24 hours (Emergency on call)',
    open24h: true,
    services: ['Stray animal rescue', 'Sterilization hospital', 'Mobile ambulance clinic'],
    lat: 19.0545, lng: 72.9155
  },

  // --- PUNE ---
  {
    name: 'RESQ Wildlife and Animal Care Hospital Pune',
    type: 'rescue_center',
    address: 'Plot No. 3902, Near Hill View Hotel, Bavdhan, Pune, Maharashtra 411021',
    city: 'Pune', district: 'Pune', state: 'Maharashtra',
    phone: '+91 93590 04272',
    email: 'info@resqct.org',
    website: 'https://resqct.org',
    openingHours: 'Open 24 hours (Emergency wildlife & pet rescue)',
    open24h: true,
    services: ['24/7 Wildlife & stray rescue', 'ICU', 'Surgery', 'Ambulance service'],
    lat: 18.5142, lng: 73.7712
  },
  {
    name: 'Government Veterinary Polyclinic Gokhale Nagar Pune',
    type: 'veterinary_hospital',
    address: 'Senapati Bapat Road, Gokhale Nagar, Pune, Maharashtra 411016',
    city: 'Pune', district: 'Pune', state: 'Maharashtra',
    phone: '+91 20 2565 6780',
    email: 'gvh.pune@maharashtra.gov.in',
    website: 'https://ahd.maharashtra.gov.in',
    openingHours: 'Open 24 hours',
    open24h: true,
    services: ['Emergency veterinary care', 'Surgical unit', 'Vaccination', 'Pathology lab'],
    lat: 18.5345, lng: 73.8315
  },
  {
    name: 'Pune Animal Welfare Society (PAWS)',
    type: 'animal_shelter',
    address: 'Kalyani Nagar, Pune, Maharashtra 411006',
    city: 'Pune', district: 'Pune', state: 'Maharashtra',
    phone: '+91 98220 37487',
    email: 'pawspune@gmail.com',
    website: 'https://pawspune.org',
    openingHours: 'Daily 9:00 am - 5:30 pm',
    open24h: false,
    services: ['Stray dog shelter', 'Cat adoption', 'Sterilization', 'Medical treatment'],
    lat: 18.5485, lng: 73.9015
  },
  {
    name: 'Society for the Prevention of Cruelty to Animals (SPCA) Pune',
    type: 'welfare_org',
    address: 'Camp, Pune, Maharashtra 411001',
    city: 'Pune', district: 'Pune', state: 'Maharashtra',
    phone: '+91 20 2636 1234',
    email: 'spcapune@gmail.com',
    website: 'https://spcapune.org',
    openingHours: 'Mon-Fri 10:00 am - 5:00 pm',
    open24h: false,
    services: ['Cruelty complaint resolution', 'Equine welfare', 'Stray protection'],
    lat: 18.5185, lng: 73.8785
  },
  {
    name: 'Animals Matter To Me (AMTM) Pune Volunteers',
    type: 'ngo',
    address: 'Viman Nagar, Pune, Maharashtra 411014',
    city: 'Pune', district: 'Pune', state: 'Maharashtra',
    phone: '+91 99203 88123',
    email: 'amtmpune@gmail.com',
    website: 'https://amtmindia.org',
    openingHours: 'Daily 8:00 am - 7:00 pm',
    open24h: false,
    services: ['Community feeding', 'Mobile wound care', 'Vaccination drives'],
    lat: 18.5625, lng: 73.9145
  }
];

export function buildSupportCenters() {
  return VERIFIED_CENTERS.map((c) => ({
    name: c.name,
    type: c.type,
    address: c.address,
    city: c.city,
    district: c.district,
    state: c.state,
    phone: c.phone,
    email: c.email || '',
    website: c.website || '',
    openingHours: c.openingHours || 'Open 24 hours',
    open24h: !!c.open24h,
    services: c.services || [],
    location: {
      type: 'Point',
      coordinates: [Number(c.lng.toFixed(5)), Number(c.lat.toFixed(5))]
    },
    isSample: false,
    isActive: true
  }));
}
